### ISSUE TITLE
Delete on Termination flag will be ignored

### ISSUE THREAD

**Issue by fotto1** [cloudsoft/brooklyn-blockstore#23]
Env:
* Brooklyn Release 0.10.0
* Cloud Provider is AWS

I create instances with the current version from brooklyn-blockstore:
```
customizers:
  - $brooklyn:object:
    - type: brooklyn.location.blockstore.NewVolumeCustomizer
      brooklyn.config:
        volumes:
        - blockDevice:
            sizeInGb: 30
            deviceSuffix: 'g'
            deleteOnTermination: true
          filesystem:
            mountPoint: /usr
            filesystemType: ext3
```

After the instances are terminated the volume still exists. Seems to be that the termination flag does not work.
